# Generated by Django 3.2.6 on 2021-08-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('FINANCE', 'FINANCE'), ('BUSINESS', 'BUSINESS'), ('AUTOBIOGRAPHY', 'AUTOBIOGRAPHY'), ('COMIC', 'COMIC'), ('PSYCHOLOGY', 'PSYCHOLOGY'), ('SOCIETY', 'SOCIETY'), ('EFFICIENCY', 'EFFICIENCY'), ('NOVEL', 'NOVEL'), ('PHILOSOPHY', 'PHILOSOPHY')], max_length=50)),
                ('another', models.CharField(choices=[('FINANCE', 'FINANCE'), ('BUSINESS', 'BUSINESS'), ('AUTOBIOGRAPHY', 'AUTOBIOGRAPHY'), ('COMIC', 'COMIC'), ('PSYCHOLOGY', 'PSYCHOLOGY'), ('SOCIETY', 'SOCIETY'), ('EFFICIENCY', 'EFFICIENCY'), ('NOVEL', 'NOVEL'), ('PHILOSOPHY', 'PHILOSOPHY')], max_length=50)),
                ('url', models.URLField()),
            ],
        ),
    ]
